---
- name: Playbook 2 - Reuse vars_files data to produce a summary report
  hosts: all
  gather_facts: false

  vars_files:
    - vars/loops-data.yml

  tasks:
    - name: Build a list of usernames using set_fact
      ansible.builtin.set_fact:
        usernames: "{{ (usernames | default([])) + [item.name] }}"
      loop: "{{ users }}"

    - name: Build a comma-separated string of usernames
      ansible.builtin.set_fact:
        usernames_csv: "{{ (usernames | default([])) | join(', ') }}"

    - name: Build a list of "service=port" strings from the map
      ansible.builtin.set_fact:
        port_pairs: "{{ (port_pairs | default([])) + [item.key ~ '=' ~ (item.value | string)] }}"
      loop: "{{ ports_map | dict2items }}"

    - name: Display a summary report using debug
      ansible.builtin.debug:
        msg:
          - "Apps list length: {{ apps_common | length }}"
          - "Usernames: {{ usernames_csv }}"
          - "Port pairs: {{ port_pairs | join(', ') }}"
          - "First site URL: {{ (sites | first).url }}"

