---
- name: Looping with vars_files data
  hosts: all
  gather_facts: false

  vars_files:
    - vars/loops-data.yml

  tasks:
    - name: Display the names from users
      ansible.builtin.debug:
        var: item.name
      loop: "{{ users }}"

    - name: Display the shells from users
      ansible.builtin.debug:
        var: item.shell
      loop: "{{ users }}"

     # Using a jinja filter "| dict2items" is costly re: speed / processing
     # Whenever possible, normalize input data to prevent needing this
    - name: Loop across a dictionary (you must use a jinja filter to transform the data)
      ansible.builtin.debug:
        var: item
      loop: "{{ ports_map | dict2items }}"
