---
- name: Playbook 1 - Loop patterns + debug + set_fact
  hosts: all
  gather_facts: false

  vars_files:
    - vars/loops-data.yml

  tasks:
    - name: Example 1 - Show each app from a list
      ansible.builtin.debug:
        msg: "Installing app (demo): {{ item }}"
      loop: "{{ apps_common }}"

    - name: Example 2 - Show user + shell from structured data
      ansible.builtin.debug:
        msg: "User: {{ item.name }} | Shell: {{ item.shell }}"
      loop: "{{ users }}"

    - name: Example 3 - Show port name and number from a map
      ansible.builtin.debug:
        msg: "Service: {{ item.key }} | Port: {{ item.value }}"
      loop: "{{ ports_map | dict2items }}"

    - name: Example 4 - Build a list of site URLs using set_fact
      ansible.builtin.set_fact:
        site_urls: "{{ (site_urls | default([])) + [item.url] }}"
      loop: "{{ sites }}"

    - name: Example 4 - Display the computed list created by set_fact
      ansible.builtin.debug:
        var: site_urls

