---
- name: Playbook 1 - Loop patterns + debug + set_fact
  hosts: all
  gather_facts: false

  vars_files:
    - vars/loops-data.yml

  tasks:
    - name: Example 0 - Use a static list
      ansible.builtin.debug:
        var: item
      loop:
       - "the loop keyword"
       - "may only be passed a list"
       - "anything else will result in an error"
      
    - name: Example 1 - Show each app from a list
      ansible.builtin.debug:
        msg: "Installing app (demo): {{ item }}"
      loop: "{{ apps_common }}"

    - name: Example 2 - Show user + shell from structured data
      ansible.builtin.debug:
        msg: "User: {{ item.name }} | Shell: {{ item.shell }}"
      loop: "{{ users }}"

    - name: Example 3 - Show port name and number from a map
      ansible.builtin.debug:
        msg: "Service: {{ item.key }} | Port: {{ item.value }}"
      loop: "{{ ports_map | dict2items }}"



